version: "2"
services:
  sonarqube:
    image: sonarqube:lts
    expose:
      - 9000
    networks:
      - default
      - reverse-proxy
    restart: always
    volumes:
      - ./conf:/opt/sonarqube/conf
      - ./data:/opt/sonarqube/data
      - ./logs:/opt/sonarqube/logs
      - ./extensions:/opt/sonarqube/extensions
    env_file:
      - .env
networks:
  reverse-proxy:
    external:
      name: reverse-proxy

